### PR TITLE
Clean merge version of #26 and #27

### PR DESCRIPTION
**Pull request by ipa-nhg**
as per subject, this PR brings together the new updates of the Ros models to include the address of the Git repository that holds the source code of the package and the definition of Ament packages.

This PR fix the current issues with the extractors, it should be merged asap!

### CODE REVIEW

**Comment by ipa-nhg** [comment]
@ipa-hsd tested with the extractors and works for the 3 ROS distros ✅ 

For example for  the turtlesim node in ROS2 I obtained:

```
PackageSet {
  AmentPackage turtlesim {
    FromGitRepo "https://github.com/ros/ros_tutorials" 
    Artifact turtlesim_node {
      Node { name turtlesim_node
        ServiceServers {
          ServiceServer { name '?' service 'turtlesim.TeleportRelative'},
          ServiceServer { name 'reset' service 'std_srvs.Empty'},
          ServiceServer { name 'kill' service 'turtlesim.Kill'},
          ServiceServer { name '?' service 'turtlesim.TeleportAbsolute'},
          ServiceServer { name 'clear' service 'std_srvs.Empty'},
          ServiceServer { name '?' service 'turtlesim.SetPen'},
          ServiceServer { name 'spawn' service 'turtlesim.Spawn'}}
        Publishers {
          Publisher { name '?' message 'turtlesim.Color'},
          Publisher { name '?' message 'turtlesim.Pose'}}
        Subscribers {
          Subscriber { name '?' message 'geometry_msgs.Twist'},
          Subscriber { name '/parameter_events' message 'rcl_interfaces.ParameterEvent'}}
}}
}}}
```

The package is identified as a AmentPackage and it adds the GitHub repository address.

**Comment by ipa-hsd** [comment]
@ipa-nhg both versions worked good!

**Review by ipa-hsd — APPROVED** [review]

**Comment by ipa-hsd** [comment]
We can add this above example with `AmentPackage` in the resources folder

**Comment by ipa-nhg** [comment]
@ipa-hsd thanks for your review, I added the turtlesim model to the resources folder!
MERGE 😃

**Pull request merged**
