### PR TITLE
Add support for CI GitHub actions

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by ipa-hsd** [comment]
The config LGTM but not sure why did the CI fail: https://travis-ci.com/github/ipa320/ros_model_parser/builds/223770588#L765

**Comment by ipa-nhg** [comment]
This is failing for travis and for github actions.

It fails for the ROS build and for the python compilation (https://github.com/ipa-nhg/ros_model_parser/actions)

This experiment was a complete success! 🎉 

Jokes aside, these are the detected errors:

- Problem with the ROS build: I am using the industrial_ci configuration, it looks like the tag condition is not supported : https://github.com/ipa320/ros_model_parser/blob/f6265d0c00dd8327183db2e065372c5a9f027f9c/package.xml#L15-L16 do you know why? I found this example https://github.com/ipa320/cob_command_tools/blob/indigo_dev/cob_command_gui/package.xml where seems to work, I have to compare both CI configurations
- Problem with the python compiler: 
  - for python 2.7 the error will be fixed by the refactor of the rossystem_metamodel_core.py):
  ```
   ./src/ros_metamodels/rossystem_metamodel_core.py:48:23: F821 undefined name 'RosParameterSet'
        self.params = RosParameterSet()
  ```
  - for python 3, we have to update the syntax for the prints:
  ```
  ./scripts/parsers/ros_parser_example.py:46:28: E999 SyntaxError: invalid syntax
    print "Package name: %s" %package_name
  ```
  
see https://github.com/ipa-nhg/ros_model_parser/runs/2402426838?check_suite_focus=true#step:5:17 for further details

**Comment by ipa-hsd** [comment]
Ah! Since I have not yet implemented `RosParameterSet`, I have commented out everything related to params locally. But did not want to push the commented code upstream.

**Comment by ipa-nhg** [comment]
> Ah! Since I have not yet implemented `RosParameterSet`, I have commented out everything related to params locally. But did not want to push the commented code upstream.

yes, no problem. No worries about that error. I know you will fix it soon, no need to add a hotfix now. 

I will check the problems with python3.

**Comment by ipa-nhg** [comment]
The problem with travis is solved, and the action for the ROS build should also work now.

I will merge this and send a new PR for the python3 support

**Comment by ipa-nhg** [comment]
The only issue with python 3 was the prints for the ros_parser_example, I made the changes directly in https://github.com/ipa320/ros_model_parser/pull/10 

The changes are: https://github.com/ipa320/ros_model_parser/pull/10/commits/e28894c48d75b621b9aa063c912d470c1076afe9

**Pull request merged**
